name: Locust Load Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

      steps:
      -  name: Checkout repository
         uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install Locust
        run: pip install locust

      - name: Run Locust Load Test
        run: |
          locust \
            --headless \
            --users 10 \
            --spawn-rate 2 \
            --run-time 30s \
            --csv=results \
            --exit-code-on-error 1

      - name: Run Locust regression test
        run: |
         locust -f locustfile.py --headless --users 10 --spawn-rate 2 --runt-time 1m --host https://localhost:8089 --only-summary --csv=test_results
        env:
          TARGET_HOST: http://your-application-url.com
        
      
      - name: Upload CSV Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: results_*.csv

